### ISSUE TITLE
Questions regarding parameters for experiments in the paper

### ISSUE THREAD

**Issue by jiong-zhu** [mims-harvard/GNNGuard#4]
I have some questions regarding the parameters you used for the experiments in the paper: 

- In Appendix E of the paper, you mentioned that you set P_0 = 0.5. I assume this is the same P_0 as used in Eq. (5) for pruning the edges after importance estimation? While in your code, as you [replied in another issue](https://github.com/mims-harvard/GNNGuard/issues/1#issuecomment-764703109), P_0 seems to be 0.1. I am wondering which one is the value, 0.1 or 0.5, that you used in the experiments in your paper? 
- I saw in [line 116 of your GCN implementation](https://github.com/mims-harvard/GNNGuard/blob/33f5390bb5adff3f8bed5bcb01e9ba50e2c74c38/defense/gcn.py#L116) that the layer-wise graph memory seems to be disabled? Is that also the case for the experiments in your paper? In other words, what are the $$\beta$$ value you used for Eq. (7) for the experiments in your paper?

**Comment by xiangzhang1015** [comment]
Hi Jiong, 

The P_0 is a hyper-parameter that users can define according to the dataset and model base they use. In particular to Cora and GCN, I found that it seems 0.1 brings better performance. 

Also, beta is another hyper-parameter that varies along with datasets. In general, I suggest using a rather small beta (like 0.05-0.1): because the GNN models are only two layers in general, the model will drop nothing with a large beta.

**Comment by yzfxmu** [comment]
> 

Hi.
I also have a question about the value of P_0.
It show that  [ in line 184](https://github.com/mims-harvard/GNNGuard/blob/33f5390bb5adff3f8bed5bcb01e9ba50e2c74c38/defense/gcn.py#L184)   you use   sim[sim<0.1] = 0, while[ in line 217](https://github.com/mims-harvard/GNNGuard/blob/33f5390bb5adff3f8bed5bcb01e9ba50e2c74c38/defense/gcn.py#L217) you set             mm = torch.nn.Threshold(0.5, 0). 
In my opinion, they shall play different roles, and which one is acttually the P_0?
